# Generated by Django 5.2.4 on 2025-08-05 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('seria_id', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='room',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='user',
        ),
        migrations.AddField(
            model_name='deal',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.RenameModel(
            old_name='Room_type',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Room_size',
            new_name='RoomSize',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.employee')),
                ('id_room_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.roomsize')),
                ('id_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='id_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configapp.room'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
